version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Update to a newer version (e.g., 16 or 18)
    commands:
      # Optional: Install global dependencies if needed (e.g., Angular CLI)
      # - npm install -g @angular/cli@8.3.5
      - npm install  # Install dependencies from package.json

  build:
    commands:
      - npm run build  # Build the project

  post_build:
    commands:
      - aws s3 sync build/ s3://bleat-transformed-leadership-stage --acl public-read --delete  # Sync to S3
      - aws cloudfront create-invalidation --distribution-id E21ZZ8IZNM9O54 --paths "/index.html"  # Invalidate CloudFront cache
